### ISSUE TITLE
Regarding your tutorial "Build a Full Stack Large Language Model Powered Chatbot: Extract Insights from Unstructured Documents"

### ISSUE THREAD

**Issue by stratosb** [pkamra/genai-chatbot-llm-rag-langchain#1]
Dear Piyali Kamra,
I am following your excellent turorial at https://community.aws/tutorials/fullstack-llm-langchain-chatbot-on-aws. 
I have completed all steps up to step 5 but there I face the following problem: the index is not created in the Amazon OpenSearch cluster as it should. 
Do you think it is a policy issue in the fargate task? I don't see any errors in CloudWatch from the Lambda Function. 
Did you face the same problem? 
Could you please help me?
Thank you for your time.

**Comment by pkamra** [comment]
Please follow the code @ https://github.com/build-on-aws/fullstack-llm-langchain-chatbot-on-aws which goes with the tutorial.   The top section of the tutorial always has the link to the code base.
<img width="380" alt="Screenshot 2023-11-08 at 3 10 52 PM" src="https://github.com/pkamra/genai-chatbot-llm-rag-langchain/assets/15902002/6ecdd40d-fef6-4658-9d10-0ce3974f0c0d">

**Comment by pkamra** [comment]
Cloing with reference to correct code base that goes with tutorial in above comment.

**Comment by pkamra** [comment]
Closing with reference to correct code base that goes with tutorial in above comment.

**Comment by stratosb** [comment]
Good morning Piyali,
I am following the code from
https://github.com/build-on-aws/fullstack-llm-langchain-chatbot-on-aws
according to the tutorial
https://community.aws/tutorials/fullstack-llm-langchain-chatbot-on-aws.
However at step 5 of the tutorial, the index carmanual is not created in
the Amazon OpenSearch cluster.
Do you think it is a policy issue in the fargate task? I don't see any
errors in CloudWatch from the Lambda Function.
Could you please help me?
Thank you for your time.

Kind Regards,
Stratos



Στις Τετ 8 Νοε 2023 στις 11:13 μ.μ., ο/η Piyali Kamra <
***@***.***> έγραψε:

**Comment by pkamra** [comment]
The fargate task definition has the correct policy. Cloudwatch Logs for the fargate task should be  at Cloudwatch logs directory /ecs/ecs-embeddings-vector in your AWS Account.  Those logs will  provide you clue if the task started and the error in your case. I did try to build the project again and the Dockerfile in create-embeddings-save-in-vectordb/ folder has been updated in the github repo to include hardcoded versions to prevent any breaking changes due to updated libraries. Please download the latest Dockerfile which should have hard coded versions mentioned like "RUN pip install --no-cache-dir  botocore==1.31.44 boto3==1.28.44 langchain==0.0.285 unstructured==0.10.12 pdf2image==1.16.3 pdfminer==20191125 pdfminer.six==20221105 "
